#!/bin/bash

echo "be sure to run this script in your current working branch"

git fetch origin

git pull origin main

git add -A > /dev/null

read -p "please enter a commit message." message

git commit -m "$message" > /dev/null

status=$?

[ $status -eq 1] && git push || echo "something went wrong, exit code: $status"




